// Generated by cbindgen from rust/sdk-poc-bindgen/yanet-cp; do not edit.
//
// C ABI of the Rust control-plane api crates. See the crate docs for the
// safety contract.

#ifndef YANET_CP_H
#define YANET_CP_H

#include <stddef.h>
#include <stdint.h>

/**
 * Version of this C ABI; bump on any change of an export or a type.
 */
#define YANET_CP_ABI_VERSION 1

/**
 * Success.
 */
#define YANET_CP_OK 0

/**
 * A null or malformed argument.
 */
#define YANET_CP_EINVAL -1

/**
 * Allocation, module setup, insert or validation failed.
 */
#define YANET_CP_EBUILD -2

/**
 * A Rust panic was caught.
 */
#define YANET_CP_EPANIC -3

/**
 * IPv4 prefix family tag.
 */
#define YANET_CP_FAMILY_IPV4 4

/**
 * IPv6 prefix family tag.
 */
#define YANET_CP_FAMILY_IPV6 6

/**
 * Library and layout facts the caller compares with its own build.
 */
typedef struct yanet_cp_abi_info {
  /**
   * `YANET_CP_ABI_VERSION` of the library.
   */
  uint32_t abi_version;
  /**
   * Dataplane module ABI version the library was generated against.
   */
  uint32_t module_abi_version;
  /**
   * Size of `struct yanet_cp_decap_prefix`.
   */
  uint32_t decap_prefix_size;
  /**
   * Size of the C module header.
   */
  uint32_t cp_module_size;
  /**
   * Size of the whole decap configuration block.
   */
  uint32_t decap_config_size;
  /**
   * Configuration layout the decap module declares to the dataplane.
   */
  uint64_t decap_config_layout;
} yanet_cp_abi_info;

/**
 * One decap prefix as an inclusive big-endian address range; IPv4 uses
 * the first four bytes of each bound.
 */
typedef struct yanet_cp_decap_prefix {
  /**
   * `YANET_CP_FAMILY_IPV4` or `YANET_CP_FAMILY_IPV6`.
   */
  uint8_t family;
  uint8_t from[16];
  uint8_t to[16];
} yanet_cp_decap_prefix;

/**
 * Fills `out` with the library's ABI and layout facts.
 *
 * # Safety
 *
 * `out` must be null or point at a writable `yanet_cp_abi_info`.
 */
int yanet_cp_abi_query(struct yanet_cp_abi_info *out);

/**
 * Builds and validates a decap configuration in the agent's memory.
 *
 * On success stores the module header in `*out` for the caller to publish
 * and later free with `yanet_cp_decap_config_free`; on failure nothing is
 * left allocated and the message goes to `err_buf`.
 *
 * # Safety
 *
 * `agent` must be an attached agent; `name` a NUL-terminated string;
 * `prefixes` null with `count` zero or `count` readable entries; `out` a
 * writable slot; `err_buf` null or `err_len` writable bytes.
 */
int yanet_cp_decap_config_build(void *agent,
                                const char *name,
                                const struct yanet_cp_decap_prefix *prefixes,
                                uintptr_t count,
                                void **out,
                                char *err_buf,
                                uintptr_t err_len);

/**
 * Destroys a decap configuration once no generation references it.
 *
 * Returns -1 with errno EAGAIN and a C error chain in `*err` while a live
 * generation still holds the module, like the C module API.
 *
 * # Safety
 *
 * `cp_module` must come from `yanet_cp_decap_config_build` and not be
 * destroyed yet; `err` must be null or a writable `yanet_error *` slot.
 */
int yanet_cp_decap_config_free(void *cp_module, void **err);

#endif  /* YANET_CP_H */
