//! Raw bindings and the whole unsafe boundary of the YANET Rust dataplane.
//!
//! The crate holds every `unsafe` block builtin Rust items need and no packet
//! logic. A device crate implements [`Device`] in safe code and exports it
//! with [`export_device!`]; the macro emits the C constructor the loader
//! resolves by name and wires it to the generic handlers below.
//!
//! Shared memory is reached only through raw pointers handed over by C.
//! Relative pointers are resolved with strict provenance: the slot gives
//! only its address and the target keeps the provenance of the pointer C
//! passed to the entry point. No reference is ever formed over bytes C may
//! mutate after publish, such as the common device header.

#![cfg_attr(not(test), no_std)]

use core::{
    ffi::{c_char, c_void},
    marker::PhantomData,
    mem::{align_of, offset_of, size_of},
    num::NonZeroUsize,
    ptr::{self, NonNull},
    slice,
};

use zerocopy::{FromBytes, Immutable};

/// Raw C declarations generated by bindgen from the repository headers.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all
)]
pub mod raw {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

unsafe extern "C" {
    fn malloc(size: usize) -> *mut c_void;
    #[link_name = "abort"]
    fn c_abort() -> !;
}

/// Terminates the process without unwinding.
pub fn abort() -> ! {
    // SAFETY: abort has no preconditions.
    unsafe { c_abort() }
}

/// What the dataplane does with a packet once a device handler returns.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Verdict {
    /// Continue to the next pipeline stage.
    Output,
    /// Release the packet and count it as dropped.
    Drop,
}

mod sealed {
    pub trait Sealed {}
}

/// A C device body whose embedding after the common device header sys
/// knows from the bound C headers.
///
/// Sealed: only sys implements it, for the bodies the C control plane
/// creates under the device type name it carries. This keeps the layout
/// facts every body read relies on out of device crates.
pub trait DeviceBody: sealed::Sealed {
    /// Device type name the C control plane creates this body under.
    const TYPE_NAME: &'static str;
    /// Byte offset of the body from the start of the device.
    const OFFSET: usize;
}

impl sealed::Sealed for raw::vxlan_device_config {}

impl DeviceBody for raw::vxlan_device_config {
    const TYPE_NAME: &'static str = "vxlan";
    const OFFSET: usize = offset_of!(raw::cp_device_vxlan, config);
}

/// A device type implemented in safe Rust.
///
/// Both handlers see one packet at a time together with the device body
/// that follows the common device header in shared memory. The body is
/// generation data: it is frozen once the control plane publishes the
/// device, and every worker reads it at once.
pub trait Device {
    /// C body this device is created with.
    type Body: DeviceBody;

    /// Rust view of the body.
    ///
    /// Any bytes are a valid value. Sys refuses to build a device whose view
    /// is larger or more strictly aligned than the C body.
    type Config: FromBytes + Immutable + Sync;

    /// Handles a packet received on the device.
    fn input(config: &Self::Config, packet: &mut Packet<'_>) -> Verdict;

    /// Handles a packet about to be transmitted through the device.
    fn output(config: &Self::Config, packet: &mut Packet<'_>) -> Verdict;
}

/// Compile-time proof that a device's view fits its C body.
struct BodyLayout<D>(PhantomData<D>);

impl<D: Device> BodyLayout<D> {
    const FITS: () = assert!(
        size_of::<D::Config>() <= size_of::<D::Body>() && align_of::<D::Config>() <= align_of::<D::Body>(),
        "the device config view must fit inside its C body"
    );
}

/// A packet exclusively owned by the running handler.
///
/// The worker owns every packet of its round and a handler sees each one
/// alone, so the frame bytes may be borrowed mutably.
pub struct Packet<'a> {
    raw: NonNull<raw::packet>,
    _round: PhantomData<&'a mut raw::packet>,
}

impl Packet<'_> {
    fn raw_data(&self) -> (*mut u8, usize) {
        let mut len = 0u16;
        // SAFETY: the packet is live and owned by this handler for the
        // round.
        let data = unsafe { raw::yanet_dp_shim_packet_data(self.raw.as_ptr(), &mut len) };
        (data, usize::from(len))
    }

    /// Returns the bytes of the first segment.
    pub fn data(&self) -> &[u8] {
        let (data, len) = self.raw_data();
        // SAFETY: the first segment holds len initialized bytes, and the
        // shared borrow of the packet keeps them unchanged.
        unsafe { slice::from_raw_parts(data, len) }
    }

    /// Returns the bytes of the first segment for in-place rewriting.
    pub fn data_mut(&mut self) -> &mut [u8] {
        let (data, len) = self.raw_data();
        // SAFETY: as for the shared view; the exclusive borrow of the packet
        // makes this the only view of the frame. The descriptor lives in the
        // headroom, outside the data.
        unsafe { slice::from_raw_parts_mut(data, len) }
    }

    /// Returns the length of the whole packet across all segments.
    pub fn total_len(&self) -> usize {
        // SAFETY: the packet is live and owned by this handler.
        let len = unsafe { raw::yanet_dp_shim_packet_len(self.raw.as_ptr()) };
        len as usize
    }

    /// Returns the flow hash the parser computed for the packet.
    pub fn hash(&self) -> u32 {
        // SAFETY: a raw field read of a live, handler-owned descriptor.
        unsafe { (&raw const (*self.raw.as_ptr()).hash).read() }
    }

    /// Grows the frame at the front and returns the new first segment.
    ///
    /// Returns `None`, leaving the frame unchanged, when the headroom above
    /// the packet descriptor is too small.
    pub fn prepend(&mut self, len: u16) -> Option<&mut [u8]> {
        // SAFETY: the packet is live and owned by this handler; the borrow
        // of the old data ended before the call.
        let data = unsafe { raw::yanet_dp_shim_packet_prepend(self.raw.as_ptr(), len) };
        if data.is_null() {
            return None;
        }
        Some(self.data_mut())
    }

    /// Removes bytes from the front of the first segment.
    ///
    /// Returns `false`, leaving the frame unchanged, when the first segment
    /// is shorter than the request.
    pub fn trim_front(&mut self, len: u16) -> bool {
        // SAFETY: the packet is live and owned by this handler.
        unsafe { raw::yanet_dp_shim_packet_adj(self.raw.as_ptr(), len) == 0 }
    }

    /// Re-runs the packet parser over the current frame.
    ///
    /// Returns `false` when the frame does not parse; such a packet must not
    /// be passed on.
    pub fn reparse(&mut self) -> bool {
        // SAFETY: the packet is live and owned by this handler.
        unsafe { raw::yanet_dp_shim_packet_parse(self.raw.as_ptr()) == 0 }
    }
}

/// Resolves a relative pointer slot within the mapping of a root pointer.
///
/// The slot contributes only its address; the result carries the provenance
/// of the root. A zero offset is the null pointer.
///
/// # Safety
///
/// The slot must be readable and the root must carry provenance for the
/// whole mapping the target lies in.
unsafe fn resolve_rel<T>(root: NonNull<u8>, slot: *const usize) -> Option<NonNull<T>> {
    // SAFETY: the caller guarantees the slot is readable.
    let offset = unsafe { slot.read() };
    if offset == 0 {
        return None;
    }
    let target = NonZeroUsize::new(slot.addr().wrapping_add(offset))?;
    Some(root.with_addr(target).cast())
}

/// Returns the device view behind a device execution context.
///
/// The device is reached through the relative device slot of the context
/// and the view is read at the C body offset; no reference covers the common
/// header.
///
/// # Safety
///
/// The context must be a published device context whose root carries
/// provenance for the shared mapping, its device must have been created
/// with the body of `D`, and the body must stay frozen while the reference
/// lives.
unsafe fn device_config<'a, D: Device>(ectx: NonNull<raw::device_ectx>) -> Option<&'a D::Config> {
    let () = BodyLayout::<D>::FITS;
    // SAFETY: a raw projection inside the live context, no reference formed.
    let slot = unsafe { &raw const (*ectx.as_ptr()).cp_device }.cast::<usize>();
    // SAFETY: the slot is a readable field of the context, and the context
    // pointer carries provenance for the whole mapping.
    let cp_device = unsafe { resolve_rel::<u8>(ectx.cast(), slot) }?;
    // SAFETY: the device embeds the C body at this offset, inside the same
    // allocation.
    let body = unsafe { cp_device.add(D::Body::OFFSET) }.cast::<D::Config>();
    debug_assert!(body.is_aligned());
    // SAFETY: the view is no larger and no more strictly aligned than the C
    // body, so it is in bounds and aligned; it is valid for any bytes and
    // has no interior mutability; the caller guarantees it stays frozen.
    Some(unsafe { body.as_ref() })
}

type Handler<D> = fn(&<D as Device>::Config, &mut Packet<'_>) -> Verdict;

/// Runs a per-packet handler over every input packet of a front.
///
/// Without a resolvable device body every packet is dropped.
///
/// # Safety
///
/// The pointers are the ones the dataplane passes to a device handler.
unsafe fn process<D: Device>(ectx: *mut raw::device_ectx, front: *mut raw::packet_front, handler: Handler<D>) {
    // SAFETY: the loader binds these handlers to the device type named
    // after the body of D, the C control plane creates devices of that type
    // with that body, and the body is frozen for the generation this round
    // runs.
    let config = NonNull::new(ectx).and_then(|ectx| unsafe { device_config::<D>(ectx) });
    loop {
        // SAFETY: the front is live and owned by this worker for the round.
        let packet = unsafe { raw::yanet_dp_shim_packet_front_pop_input(front) };
        let Some(raw_packet) = NonNull::new(packet) else {
            break;
        };
        let verdict = match config {
            Some(config) => handler(config, &mut Packet { raw: raw_packet, _round: PhantomData }),
            None => Verdict::Drop,
        };
        // SAFETY: the packet was popped from this front and is linked back
        // exactly once.
        unsafe {
            match verdict {
                Verdict::Output => raw::yanet_dp_shim_packet_front_output(front, packet),
                Verdict::Drop => raw::yanet_dp_shim_packet_front_drop(front, packet),
            }
        }
    }
}

unsafe extern "C" fn input_handler<D: Device>(
    _dp_worker: *mut raw::dp_worker,
    ectx: *mut raw::device_ectx,
    front: *mut raw::packet_front,
) {
    // SAFETY: called by the dataplane with handler arguments.
    unsafe { process::<D>(ectx, front, D::input) }
}

unsafe extern "C" fn output_handler<D: Device>(
    _dp_worker: *mut raw::dp_worker,
    ectx: *mut raw::device_ectx,
    front: *mut raw::packet_front,
) {
    // SAFETY: called by the dataplane with handler arguments.
    unsafe { process::<D>(ectx, front, D::output) }
}

unsafe extern "C" fn commit_handler(_dp_config: *mut raw::dp_config, _cp_device: *mut raw::cp_device) {}

/// Allocates the descriptor the device loader expects from a constructor.
///
/// The descriptor carries the type name of the C body, so the loader binds
/// the handlers to devices created with that body. The loader copies the
/// descriptor and releases it with the C allocator, so it is allocated with
/// the C allocator too. Returns null when the allocation fails.
pub fn new_device<D: Device>() -> *mut raw::device {
    let () = BodyLayout::<D>::FITS;
    let mut type_name = [0 as c_char; raw::DEVICE_TYPE_LEN as usize];
    let max_len = type_name.len() - 1;
    for (dst, src) in type_name.iter_mut().zip(D::Body::TYPE_NAME.bytes().take(max_len)) {
        *dst = src as c_char;
    }
    let device = raw::device {
        name: type_name,
        input_handler: Some(input_handler::<D>),
        output_handler: Some(output_handler::<D>),
        commit_handler: Some(commit_handler),
    };
    // SAFETY: malloc has no preconditions.
    let ptr = unsafe { malloc(size_of::<raw::device>()) }.cast::<raw::device>();
    if ptr.is_null() {
        return ptr::null_mut();
    }
    // SAFETY: the fresh allocation is large enough and malloc-aligned.
    unsafe { ptr.write(device) };
    ptr
}

/// Reports whether two strings are equal, in a constant context.
#[doc(hidden)]
pub const fn same_name(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut idx = 0;
    while idx < a.len() {
        if a[idx] != b[idx] {
            return false;
        }
        idx += 1;
    }
    true
}

/// Exports a [`Device`] implementation as the builtin device type `name`.
///
/// Emits the `new_device_<name>` constructor the dataplane resolves from
/// its own binary, and fails the build unless `name` is the type name of
/// the device's C body. Accepts only an identifier and a type path, so the
/// caller cannot inject code into the exported item.
///
/// A view larger than the C body does not build:
///
/// ```compile_fail
/// use yanet_dp_sys::{Device, Packet, Verdict, raw};
///
/// struct Big;
///
/// impl Device for Big {
///     type Body = raw::vxlan_device_config;
///     type Config = [u8; 4096];
///
///     fn input(_: &[u8; 4096], _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
///
///     fn output(_: &[u8; 4096], _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
/// }
///
/// yanet_dp_sys::export_device!(vxlan, Big);
/// ```
///
/// Neither does a name other than the type name of the body:
///
/// ```compile_fail
/// use yanet_dp_sys::{Device, Packet, Verdict, raw};
///
/// #[derive(zerocopy::FromBytes, zerocopy::Immutable)]
/// #[repr(C)]
/// struct Vni(u32);
///
/// struct Misnamed;
///
/// impl Device for Misnamed {
///     type Body = raw::vxlan_device_config;
///     type Config = Vni;
///
///     fn input(_: &Vni, _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
///
///     fn output(_: &Vni, _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
/// }
///
/// yanet_dp_sys::export_device!(vlan, Misnamed);
/// ```
#[macro_export]
macro_rules! export_device {
    ($name:ident, $device:path) => {
        const _: () = {
            assert!(
                $crate::same_name(
                    stringify!($name),
                    <<$device as $crate::Device>::Body as $crate::DeviceBody>::TYPE_NAME,
                ),
                "the exported name must be the type name of the device body",
            );

            #[unsafe(export_name = concat!("new_device_", stringify!($name)))]
            extern "C" fn new_device() -> *mut $crate::raw::device {
                $crate::new_device::<$device>()
            }
        };
    };
}

#[cfg(test)]
mod tests;
