//! Raw bindings and the unsafe boundary of the YANET Rust dataplane.
//!
//! Together with `yanet-shm` the crate holds every `unsafe` block builtin
//! Rust items need, and no packet logic. It knows no device body: a device
//! is the generic item of the C header and the device's own `ShmLayout`
//! body. A device crate implements [`Device`] in safe code and
//! exports it with [`export_device!`]; the macro emits the C constructor the
//! loader resolves by name and wires it to the generic handlers below.
//!
//! Shared memory is reached only through raw pointers handed over by C.
//! Relative pointers are resolved with strict provenance: the slot gives
//! only its address and the target keeps the provenance of the pointer C
//! passed to the entry point. The C header sits in an `Opaque` cell, so a
//! reference to the whole item stays sound while C mutates the header after
//! publish.
//!
//! The dataplane interprets a device as the item of a body `B` only for the
//! device type it registered, and the control plane can create a device of
//! that type only by presenting `B`'s fingerprint, which the C device init
//! compares with the one the type was loaded with (as kernel module
//! versioning binds a module to the kernel it was built for).

#![cfg_attr(not(test), no_std)]

use core::{
    ffi::{c_char, c_void},
    marker::PhantomData,
    mem::size_of,
    num::NonZeroUsize,
    ptr::{self, NonNull},
    slice,
};

pub use yanet_shm;
use yanet_shm::{ShmItem, ShmLayout};

/// Raw C declarations generated by bindgen from the repository headers.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::all
)]
pub mod raw {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

unsafe extern "C" {
    fn malloc(size: usize) -> *mut c_void;
    #[link_name = "abort"]
    fn c_abort() -> !;
}

/// Terminates the process without unwinding.
pub fn abort() -> ! {
    // SAFETY: abort has no preconditions.
    unsafe { c_abort() }
}

/// What the dataplane does with a packet once a device handler returns.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Verdict {
    /// Continue to the next pipeline stage.
    Output,
    /// Release the packet and count it as dropped.
    Drop,
}

/// A device type implemented in safe Rust.
///
/// Both handlers see one packet at a time together with the device body
/// the Rust control plane wrote after the common device header. The body is
/// generation data: it is frozen once the control plane publishes the
/// device, and every worker reads it at once.
pub trait Device {
    /// Device type name, as registered with the dataplane.
    const NAME: &'static str;

    /// Device body; its fingerprint is the layout the device type is
    /// registered with.
    type Config: ShmLayout + Sync;

    /// Handles a packet received on the device.
    fn input(config: &Self::Config, packet: &mut Packet<'_>) -> Verdict;

    /// Handles a packet about to be transmitted through the device.
    fn output(config: &Self::Config, packet: &mut Packet<'_>) -> Verdict;
}

/// The shared-memory device of a Rust device type.
pub type DeviceItem<B> = ShmItem<raw::cp_device, B>;

/// Device type names the dataplane already registers for C devices.
const C_DEVICE_NAMES: [&str; 3] = ["plain", "vlan", "trafgen"];

/// A packet exclusively owned by the running handler.
///
/// The worker owns every packet of its round and a handler sees each one
/// alone, so the frame bytes may be borrowed mutably.
pub struct Packet<'a> {
    raw: NonNull<raw::packet>,
    _round: PhantomData<&'a mut raw::packet>,
}

impl Packet<'_> {
    fn raw_data(&self) -> (*mut u8, usize) {
        let mut len = 0u16;
        // SAFETY: the packet is live and owned by this handler for the
        // round.
        let data = unsafe { raw::yanet_dp_shim_packet_data(self.raw.as_ptr(), &mut len) };
        (data, usize::from(len))
    }

    /// Returns the bytes of the first segment.
    pub fn data(&self) -> &[u8] {
        let (data, len) = self.raw_data();
        // SAFETY: the first segment holds len initialized bytes, and the
        // shared borrow of the packet keeps them unchanged.
        unsafe { slice::from_raw_parts(data, len) }
    }

    /// Returns the bytes of the first segment for in-place rewriting.
    pub fn data_mut(&mut self) -> &mut [u8] {
        let (data, len) = self.raw_data();
        // SAFETY: as for the shared view; the exclusive borrow of the packet
        // makes this the only view of the frame. The descriptor lives in the
        // headroom, outside the data.
        unsafe { slice::from_raw_parts_mut(data, len) }
    }

    /// Returns the length of the whole packet across all segments.
    pub fn total_len(&self) -> usize {
        // SAFETY: the packet is live and owned by this handler.
        let len = unsafe { raw::yanet_dp_shim_packet_len(self.raw.as_ptr()) };
        len as usize
    }

    /// Returns the flow hash the parser computed for the packet.
    pub fn hash(&self) -> u32 {
        // SAFETY: a raw field read of a live, handler-owned descriptor.
        unsafe { (&raw const (*self.raw.as_ptr()).hash).read() }
    }

    /// Grows the frame at the front and returns the new first segment.
    ///
    /// Returns `None`, leaving the frame unchanged, when the headroom above
    /// the packet descriptor is too small.
    pub fn prepend(&mut self, len: u16) -> Option<&mut [u8]> {
        // SAFETY: the packet is live and owned by this handler; the borrow
        // of the old data ended before the call.
        let data = unsafe { raw::yanet_dp_shim_packet_prepend(self.raw.as_ptr(), len) };
        if data.is_null() {
            return None;
        }
        Some(self.data_mut())
    }

    /// Removes bytes from the front of the first segment.
    ///
    /// Returns `false`, leaving the frame unchanged, when the first segment
    /// is shorter than the request.
    pub fn trim_front(&mut self, len: u16) -> bool {
        // SAFETY: the packet is live and owned by this handler.
        unsafe { raw::yanet_dp_shim_packet_adj(self.raw.as_ptr(), len) == 0 }
    }

    /// Re-runs the packet parser over the current frame.
    ///
    /// Returns `false` when the frame does not parse; such a packet must not
    /// be passed on.
    pub fn reparse(&mut self) -> bool {
        // SAFETY: the packet is live and owned by this handler.
        unsafe { raw::yanet_dp_shim_packet_parse(self.raw.as_ptr()) == 0 }
    }
}

/// Resolves a relative pointer slot within the mapping of a root pointer.
///
/// The slot contributes only its address; the result carries the provenance
/// of the root. A zero offset is the null pointer.
///
/// # Safety
///
/// The slot must be readable and the root must carry provenance for the
/// whole mapping the target lies in.
unsafe fn resolve_rel<T>(root: NonNull<u8>, slot: *const usize) -> Option<NonNull<T>> {
    // SAFETY: the caller guarantees the slot is readable.
    let offset = unsafe { slot.read() };
    if offset == 0 {
        return None;
    }
    let target = NonZeroUsize::new(slot.addr().wrapping_add(offset))?;
    Some(root.with_addr(target).cast())
}

/// Returns the device behind a device execution context.
///
/// The device is reached through the relative device slot of the context.
///
/// # Safety
///
/// The context must be a published device context whose root carries
/// provenance for the shared mapping, and its device must be of the type
/// `D` is registered under: such a device was initialized for the layout of
/// `D::Config`. The body must stay frozen while the reference lives.
unsafe fn device_item<'a, D: Device>(ectx: NonNull<raw::device_ectx>) -> Option<&'a DeviceItem<D::Config>> {
    // SAFETY: a raw projection inside the live context, no reference formed.
    let slot = unsafe { &raw const (*ectx.as_ptr()).cp_device }.cast::<usize>();
    // SAFETY: the slot is a readable field of the context, and the context
    // pointer carries provenance for the whole mapping.
    let item = unsafe { resolve_rel::<DeviceItem<D::Config>>(ectx.cast(), slot) }?;
    debug_assert!(item.is_aligned());
    // SAFETY: the device was created for this layout, so the item is in
    // bounds and a valid value for any bytes; the C header sits in a cell,
    // and the caller guarantees the body stays frozen.
    Some(unsafe { item.as_ref() })
}

type Handler<D> = fn(&<D as Device>::Config, &mut Packet<'_>) -> Verdict;

/// Runs a per-packet handler over every input packet of a front.
///
/// Without a resolvable device body every packet is dropped.
///
/// # Safety
///
/// The pointers are the ones the dataplane passes to a device handler.
unsafe fn process<D: Device>(ectx: *mut raw::device_ectx, front: *mut raw::packet_front, handler: Handler<D>) {
    // SAFETY: the loader binds these handlers to devices of the type D is
    // registered under, and the body is frozen for the generation this
    // round runs.
    let config = NonNull::new(ectx)
        .and_then(|ectx| unsafe { device_item::<D>(ectx) })
        .map(|item| &item.body);
    loop {
        // SAFETY: the front is live and owned by this worker for the round.
        let packet = unsafe { raw::yanet_dp_shim_packet_front_pop_input(front) };
        let Some(raw_packet) = NonNull::new(packet) else {
            break;
        };
        let verdict = match config {
            Some(config) => handler(config, &mut Packet { raw: raw_packet, _round: PhantomData }),
            None => Verdict::Drop,
        };
        // SAFETY: the packet was popped from this front and is linked back
        // exactly once.
        unsafe {
            match verdict {
                Verdict::Output => raw::yanet_dp_shim_packet_front_output(front, packet),
                Verdict::Drop => raw::yanet_dp_shim_packet_front_drop(front, packet),
            }
        }
    }
}

unsafe extern "C" fn input_handler<D: Device>(
    _dp_worker: *mut raw::dp_worker,
    ectx: *mut raw::device_ectx,
    front: *mut raw::packet_front,
) {
    // SAFETY: called by the dataplane with handler arguments.
    unsafe { process::<D>(ectx, front, D::input) }
}

unsafe extern "C" fn output_handler<D: Device>(
    _dp_worker: *mut raw::dp_worker,
    ectx: *mut raw::device_ectx,
    front: *mut raw::packet_front,
) {
    // SAFETY: called by the dataplane with handler arguments.
    unsafe { process::<D>(ectx, front, D::output) }
}

unsafe extern "C" fn commit_handler(_dp_config: *mut raw::dp_config, _cp_device: *mut raw::cp_device) {}

/// Allocates the descriptor the device loader expects from a constructor.
///
/// The descriptor carries the type name of `D` and the fingerprint of its
/// body, so the loader binds the handlers to devices of that type and the
/// control plane can create such devices only for that layout. The loader
/// copies the descriptor and releases it with the C allocator, so it is
/// allocated with the C allocator too. Returns null when the allocation fails.
pub fn new_device<D: Device>() -> *mut raw::device {
    let mut type_name = [0 as c_char; raw::DEVICE_TYPE_LEN as usize];
    let max_len = type_name.len() - 1;
    for (dst, src) in type_name.iter_mut().zip(D::NAME.bytes().take(max_len)) {
        *dst = src as c_char;
    }
    let device = raw::device {
        name: type_name,
        input_handler: Some(input_handler::<D>),
        output_handler: Some(output_handler::<D>),
        commit_handler: Some(commit_handler),
        config_layout: <D::Config as ShmLayout>::FINGERPRINT,
    };
    // SAFETY: malloc has no preconditions.
    let ptr = unsafe { malloc(size_of::<raw::device>()) }.cast::<raw::device>();
    if ptr.is_null() {
        return ptr::null_mut();
    }
    // SAFETY: the fresh allocation is large enough and malloc-aligned.
    unsafe { ptr.write(device) };
    ptr
}

/// Reports whether two strings are equal, in a constant context.
#[doc(hidden)]
pub const fn same_name(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut idx = 0;
    while idx < a.len() {
        if a[idx] != b[idx] {
            return false;
        }
        idx += 1;
    }
    true
}

/// Reports whether a name is free for a Rust device type, in a constant
/// context: not taken by a C device and shorter than the C type name field.
///
/// The list of C device names mirrors the dataplane's builtin list and must
/// move with it.
#[doc(hidden)]
pub const fn free_device_name(name: &str) -> bool {
    let mut idx = 0;
    while idx < C_DEVICE_NAMES.len() {
        if same_name(name, C_DEVICE_NAMES[idx]) {
            return false;
        }
        idx += 1;
    }
    !name.is_empty() && name.len() < raw::DEVICE_TYPE_LEN as usize
}

/// Exports a [`Device`] implementation as the builtin device type `name`.
///
/// Emits the `new_device_<name>` constructor the dataplane resolves from
/// its own binary, and fails the build unless `name` is the device's own
/// name and no C device uses it. Accepts only an identifier and a type
/// path, so the caller cannot inject code into the exported item.
///
/// A name other than the device's own does not build:
///
/// ```compile_fail
/// use yanet_dp_sys::{Device, Packet, Verdict};
///
/// struct Tunnel;
///
/// impl Device for Tunnel {
///     const NAME: &'static str = "tunnel";
///     type Config = u32;
///
///     fn input(_: &u32, _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
///
///     fn output(_: &u32, _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
/// }
///
/// yanet_dp_sys::export_device!(vxlan, Tunnel);
/// ```
///
/// Neither does the name of a C device:
///
/// ```compile_fail
/// use yanet_dp_sys::{Device, Packet, Verdict};
///
/// struct Vlan;
///
/// impl Device for Vlan {
///     const NAME: &'static str = "vlan";
///     type Config = u32;
///
///     fn input(_: &u32, _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
///
///     fn output(_: &u32, _: &mut Packet<'_>) -> Verdict {
///         Verdict::Drop
///     }
/// }
///
/// yanet_dp_sys::export_device!(vlan, Vlan);
/// ```
#[macro_export]
macro_rules! export_device {
    ($name:ident, $device:path) => {
        const _: () = {
            assert!(
                $crate::same_name(stringify!($name), <$device as $crate::Device>::NAME),
                "the exported name must be the device's own name",
            );
            assert!(
                $crate::free_device_name(stringify!($name)),
                "the device name is taken by a C device or does not fit",
            );
            assert!(
                <<$device as $crate::Device>::Config as $crate::yanet_shm::ShmLayout>::FINGERPRINT != 0,
                "the zero layout is the one of C devices",
            );

            #[unsafe(export_name = concat!("new_device_", stringify!($name)))]
            extern "C" fn new_device() -> *mut $crate::raw::device {
                $crate::new_device::<$device>()
            }
        };
    };
}

#[cfg(test)]
mod tests;
