package main

import (
	"fmt"
	"strings"
)

const generatedNotice = "// Code generated by abigen. DO NOT EDIT."

const defaultSymbolPrefix = "yanet_module_abi_"

const abiTableFormatVersion = 1

const exportAttribute = `__attribute__((visibility("default")))`

func generateManifestC(rows []entityRow, manifestText, symbolPrefix string) string {
	entitiesSymbol := fmt.Sprintf("%sentities_v%d", symbolPrefix, abiTableFormatVersion)
	countSymbol := fmt.Sprintf("%scount_v%d", symbolPrefix, abiTableFormatVersion)
	manifestSymbol := symbolPrefix + "manifest"

	var b strings.Builder
	b.WriteString(generatedNotice)
	b.WriteByte('\n')
	b.WriteString("#include \"lib/dataplane/config/plugin_abi.h\"\n\n")

	fmt.Fprintf(&b, "%s const struct yanet_abi_entity %s[] = {\n", exportAttribute, entitiesSymbol)
	for _, row := range rows {
		fmt.Fprintf(&b, "\t{%s, %s},\n", cStringLiteral(row.Name), cStringLiteral(row.Hash))
	}

	b.WriteString("};\n\n")

	fmt.Fprintf(&b, "%s const size_t %s = sizeof(%s) / sizeof(%s[0]);\n", exportAttribute, countSymbol, entitiesSymbol, entitiesSymbol)
	fmt.Fprintf(&b, "%s const char %s[] = %s;\n", exportAttribute, manifestSymbol, cStringLiteral(manifestText))
	return b.String()
}

func cStringLiteral(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"', '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString(`\n`)
		default:
			b.WriteRune(r)
		}
	}

	b.WriteByte('"')
	return b.String()
}
