syntax = "proto3";

package balancerpb;

import "modules/balancer/controlplane/balancerpb/common.proto";

option go_package = "github.com/yanet-platform/yanet2/modules/balancer/controlplane/balancerpb;balancerpb";

// Memory usage for real servers within a VS
message RealsUsage {
	uint64 counters = 1;
	uint64 interval_counters = 2;
	uint64 data = 3;
	uint64 total = 4;
}

// Memory usage for a single virtual service
message VsUsage {
	uint64 acl = 1;
	uint64 ring = 2;
	uint64 counters = 3;
	RealsUsage reals = 4;
	uint64 other = 5;
	uint64 total = 6;
}

// Named VS inspect with identifier
message NamedVsUsage {
	VsIdentifier identifier = 1;
	VsUsage inspect = 2;
}

message PacketHandlerVsUsage {
	uint64 matcher = 1;
	uint64 summary_vs = 2;
	repeated NamedVsUsage vs = 3;
	uint64 index = 4;
	uint64 total = 5;
}

message PacketHandlerUsage {
	repeated NamedVsUsage vs = 1;
	uint64 summary_vs = 3;
	uint64 vs_index = 4;
	uint64 reals_index = 5;
	uint64 counters = 6;
	uint64 interval_counters = 7;
	uint64 decap_usage = 8;
	uint64 total_usage = 9;
}

message BalancerMemoryUsage {
	string name = 1;
	PacketHandlerUsage packet_handler = 2;
	uint64 session_table = 3;
	uint64 other = 4;
	uint64 total = 5;
}

message AgentMemoryUsage {
	uint64 memory_limit = 1;
	uint64 memory_usage = 2;
	repeated BalancerMemoryUsage balancers = 3;
}