package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// writeGoFile creates a Go source file with the given content inside a
// temporary directory and returns its path.
func writeGoFile(t *testing.T, content string) string {
	t.Helper()

	dir := t.TempDir()
	path := filepath.Join(dir, "source.go")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	return path
}

// TestLintGoFile verifies lintGoFile against a table of Go source snippets,
// each checked for the exact set of violation names it must produce.
func TestLintGoFile(t *testing.T) {
	tests := []struct {
		name          string
		source        string
		expectedNames []string
	}{
		{
			name: "constructor flagged",
			source: `package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int {
	return nil
}
`,
			expectedNames: []string{"NewFoo"},
		},
		{
			name: "method flagged",
			source: `package foo

import "go.uber.org/zap"

type Foo struct{}

func (m *Foo) Configure(log *zap.Logger) error {
	return nil
}
`,
			expectedNames: []string{"Foo.Configure"},
		},
		{
			name: "free function clean",
			source: `package foo

import "go.uber.org/zap"

func Process(log *zap.Logger) error {
	return nil
}
`,
		},
		{
			name: "options-pattern helper clean",
			source: `package foo

import "go.uber.org/zap"

type Option func(*options)

type options struct{}

func WithLog(log *zap.Logger) Option {
	return nil
}
`,
		},
		{
			name: "logger in results clean",
			source: `package foo

import "go.uber.org/zap"

type Config struct{}

func Init(cfg *Config) (*zap.Logger, zap.AtomicLevel, error) {
	return nil, zap.AtomicLevel{}, nil
}
`,
		},
		{
			name: "logger struct field clean",
			source: `package foo

import "go.uber.org/zap"

type Foo struct {
	log *zap.Logger
}

func NewFoo() *Foo {
	return &Foo{}
}
`,
		},
		{
			name: "aliased import flagged",
			source: `package foo

import zaplog "go.uber.org/zap"

func NewFoo(log *zaplog.Logger) *int {
	return nil
}
`,
			expectedNames: []string{"NewFoo"},
		},
		{
			name: "nested callback flagged",
			source: `package foo

import "go.uber.org/zap"

func NewFoo(factory func(*zap.Logger) error) *int {
	return nil
}
`,
			expectedNames: []string{"NewFoo"},
		},
		{
			name: "variadic flagged",
			source: `package foo

import "go.uber.org/zap"

func NewFoo(logs ...*zap.Logger) *int {
	return nil
}
`,
			expectedNames: []string{"NewFoo"},
		},
		{
			name: "interface method flagged",
			source: `package foo

import "go.uber.org/zap"

type Service interface {
	Configure(log *zap.Logger) error
}
`,
			expectedNames: []string{"Service.Configure"},
		},
		{
			name: "generic callback clean",
			source: `package foo

import "go.uber.org/zap"

type Runnable interface{}

func Run[C any](use, short string, factory func(*C, *zap.Logger) (Runnable, error)) error {
	return nil
}
`,
		},
		{
			name: "word-fragment near-misses clean",
			source: `package foo

import "go.uber.org/zap"

func NewsFeed(log *zap.Logger) *int {
	return nil
}

func newlineSplitter(log *zap.Logger) *int {
	return nil
}
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := writeGoFile(t, tt.source)

			violations, err := lintGoFile(path)
			require.NoError(t, err)

			var names []string
			for _, v := range violations {
				names = append(names, v.Name)
			}
			require.Equal(t, tt.expectedNames, names)
		})
	}
}

// TestScanSkipsTestAndGeneratedFiles verifies that _test.go files and files
// carrying the standard "Code generated ... DO NOT EDIT." marker are
// skipped by the directory walk.
func TestScanSkipsTestAndGeneratedFiles(t *testing.T) {
	root := t.TempDir()

	testFile := filepath.Join(root, "foo_test.go")
	require.NoError(t, os.WriteFile(testFile, []byte(`package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int { return nil }
`), 0o644))

	generatedFile := filepath.Join(root, "generated.go")
	require.NoError(t, os.WriteFile(generatedFile, []byte(`// Code generated by protoc-gen-go. DO NOT EDIT.
package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int { return nil }
`), 0o644))

	violations, err := scan(root, nil)
	require.NoError(t, err)
	require.Empty(t, violations)
}

// TestScanSkipsDotDirectories verifies that a violation inside a
// dot-prefixed directory, such as a gitignored nested checkout, is not
// reported.
func TestScanSkipsDotDirectories(t *testing.T) {
	root := t.TempDir()

	dotDir := filepath.Join(root, ".claude", "x")
	require.NoError(t, os.MkdirAll(dotDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dotDir, "mod.go"), []byte(`package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int { return nil }
`), 0o644))

	violations, err := scan(root, nil)
	require.NoError(t, err)
	require.Empty(t, violations)
}

// TestScanSkipsUnderscoreDirectories verifies that a violation inside an
// underscore-prefixed directory is not reported, matching the convention
// used by the Go toolchain itself.
func TestScanSkipsUnderscoreDirectories(t *testing.T) {
	root := t.TempDir()

	underscoreDir := filepath.Join(root, "_scratch")
	require.NoError(t, os.MkdirAll(underscoreDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(underscoreDir, "mod.go"), []byte(`package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int { return nil }
`), 0o644))

	violations, err := scan(root, nil)
	require.NoError(t, err)
	require.Empty(t, violations)
}

// TestScanReportsViolationAtDotPrefixedRoot verifies that a violation in a
// file directly at the scan root is still reported even when the root
// itself has a dot-prefixed basename.
//
// This guards against the walk callback skipping the root as if it were an
// excluded dot-directory, which would silently scan zero files.
func TestScanReportsViolationAtDotPrefixedRoot(t *testing.T) {
	root := filepath.Join(t.TempDir(), ".hidden")
	require.NoError(t, os.MkdirAll(root, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, "mod.go"), []byte(`package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int { return nil }
`), 0o644))

	violations, err := scan(root, nil)
	require.NoError(t, err)
	require.Len(t, violations, 1)
	require.Equal(t, "NewFoo", violations[0].Name)
}

// TestScanRespectsExcludeFlag verifies that a directory passed via the
// --exclude flag is skipped, while a sibling directory is still scanned.
func TestScanRespectsExcludeFlag(t *testing.T) {
	root := t.TempDir()

	source := `package foo

import "go.uber.org/zap"

func NewFoo(log *zap.Logger) *int { return nil }
`

	excludedDir := filepath.Join(root, "excluded")
	require.NoError(t, os.MkdirAll(excludedDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(excludedDir, "mod.go"), []byte(source), 0o644))

	includedDir := filepath.Join(root, "included")
	require.NoError(t, os.MkdirAll(includedDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(includedDir, "mod.go"), []byte(source), 0o644))

	violations, err := scan(root, []string{excludedDir})
	require.NoError(t, err)
	require.Len(t, violations, 1)
	require.Equal(t, filepath.Join(includedDir, "mod.go"), violations[0].Path)
}

// TestReportAllowlistSuppressesViolation verifies that an allowlist entry
// with a reason suppresses its matching violation and yields a clean run.
func TestReportAllowlistSuppressesViolation(t *testing.T) {
	allowlistPath := filepath.Join(t.TempDir(), "allowlist.txt")
	require.NoError(t, os.WriteFile(allowlistPath, []byte(
		"foo.go:NewFoo  # legacy: migrate to the options pattern\n",
	), 0o644))

	violations := []violation{{Key: "foo.go:NewFoo", Path: "foo.go", Line: 3, Name: "NewFoo"}}

	failed := report(violations, allowlistPath)
	require.False(t, failed)
}

// TestReportStaleAllowlistEntryFails verifies that an allowlist entry with
// no matching violation is reported as a stale-entry failure.
func TestReportStaleAllowlistEntryFails(t *testing.T) {
	allowlistPath := filepath.Join(t.TempDir(), "allowlist.txt")
	require.NoError(t, os.WriteFile(allowlistPath, []byte(
		"foo.go:NewFoo  # legacy: migrate to the options pattern\n",
	), 0o644))

	failed := report(nil, allowlistPath)
	require.True(t, failed)
}

// TestReportMissingReasonFails verifies that an allowlist entry without a
// "# reason" suffix is itself a lint failure.
func TestReportMissingReasonFails(t *testing.T) {
	allowlistPath := filepath.Join(t.TempDir(), "allowlist.txt")
	require.NoError(t, os.WriteFile(allowlistPath, []byte(
		"foo.go:NewFoo\n",
	), 0o644))

	violations := []violation{{Key: "foo.go:NewFoo", Path: "foo.go", Line: 3, Name: "NewFoo"}}

	failed := report(violations, allowlistPath)
	require.True(t, failed)
}

// TestReportDuplicateAllowlistEntryFails verifies that a repeated allowlist
// key is reported as a failure instead of silently overwriting the earlier
// row, so a duplicated ledger entry cannot hide from review.
func TestReportDuplicateAllowlistEntryFails(t *testing.T) {
	allowlistPath := filepath.Join(t.TempDir(), "allowlist.txt")
	require.NoError(t, os.WriteFile(allowlistPath, []byte(
		"foo.go:NewFoo  # legacy: migrate to the options pattern\n"+
			"foo.go:NewFoo  # duplicate row\n",
	), 0o644))

	violations := []violation{{Key: "foo.go:NewFoo", Path: "foo.go", Line: 3, Name: "NewFoo"}}

	failed := report(violations, allowlistPath)
	require.True(t, failed)
}
