syntax = "proto3";

package aclpb;

import "common/proto/target.proto";

option go_package = "github.com/yanet-platform/yanet2/modules/"
		    "acl/controlplane/aclpb;aclpb";

service ACLService {
	// Enable ACL
	rpc EnableAcl(EnableAclRequest) returns (EnableAclResponse);
	// Updates the complete ACL configuration with a new set of rules
	rpc UpdateConfig(UpdateConfigRequest) returns (UpdateConfigResponse);
}

message EnableAclRequest {
	commonpb.TargetModule target = 1;
	repeated Rule rules = 2;
}

message EnableAclResponse {
}

message UpdateConfigRequest {
	commonpb.TargetModule target = 1;
	repeated Rule rules = 2;
}

message UpdateConfigResponse {
}

message Rule {
	// Traffic matching criteria
	Filter filter = 1;
	// Action to take when traffic matches the filter
	ActionKind action = 2;
	uint32 skip_to_count = 3;
	bool log = 4;
}

message Filter {
	repeated IPNet src6s = 1;
	repeated IPNet dst6s = 2;
	repeated IPNet src4s = 3;
	repeated IPNet dst4s = 4;
	repeated PortRange src_port_ranges = 5;
	repeated PortRange dst_port_ranges = 6;
	// List of network device names where this rule applies
	repeated string devices = 7;
	// List of protocol ranges to match
	// Can match specific protocols or protocol+flag combinations
	repeated ProtoRange proto_ranges = 8;
	bool keep_state = 9;
	// For hitcount; pass and deny only
	string hash_id = 10;
}

message IPNet {
	// IP address in network byte order
	// 4 bytes for IPv4, 16 bytes for IPv6
	bytes ip = 1;
	// Network prefix length in bits (e.g., 24 for 10.0.0.0/24)
	uint32 prefix_len = 2;
}

// Represents a TCP/UDP port range [from; to]
message PortRange {
	uint32 from = 1;
	uint32 to = 2;
}

// Represents a protocol number range [from; to]
// For transport protocols, upper byte may contain flag bits
message ProtoRange {
	uint32 from = 1;
	uint32 to = 2;
}

// Defines possible actions for matched traffic
enum ActionKind {
	ACTION_KIND_UNSPECIFIED = 0;
	ACTION_KIND_PASS = 1;
	ACTION_KIND_DENY = 2;
	ACTION_KIND_COUNT = 3;
	ACTION_KIND_CHECK_STATE = 5;
}
