syntax = "proto3";

package ynpb;

option go_package = "github.com/yanet-platform/yanet2/controlplane/ynpb;ynpb";

service CountersService {
	// Inspect retrieves the current configuration state.
	rpc Device(DeviceCountersRequest) returns (CountersResponse) {
	}
	rpc Pipeline(PipelineCountersRequest) returns (CountersResponse) {
	}
	rpc Function(FunctionCountersRequest) returns (CountersResponse) {
	}
	rpc Chain(ChainCountersRequest) returns (CountersResponse) {
	}
	rpc Module(ModuleCountersRequest) returns (CountersResponse) {
	}
	rpc AggregateModule(AggregateModuleCountersRequest) returns 
		(AggregateModuleCountersResponse) {}
}

message DeviceCountersRequest {
	string device = 1;
}

message PipelineCountersRequest {
	string device = 1;
	string pipeline = 2;
}

message FunctionCountersRequest {
	string device = 1;
	string pipeline = 2;
	string function = 3;
}

message ChainCountersRequest {
	string device = 1;
	string pipeline = 2;
	string function = 3;
	string chain = 4;
}

message ModuleCountersRequest {
	string device = 1;
	string pipeline = 2;
	string function = 3;
	string chain = 4;
	string module_type = 5;
	string module_name = 6;
	// CounterQuery filters counters by name. If empty, returns all
	// counters.
	//
	// TODO: support wildcards or regex?
	repeated string counter_query = 7;
}

message CounterInstanceInfo {
	repeated uint64 values = 1;
}

message CounterInfo {
	string name = 1;
	repeated CounterInstanceInfo instances = 2;
}

message CountersResponse {
	repeated CounterInfo counters = 1;
}

message AggregateModuleCountersRequest {
	string device = 1;
	string pipeline = 2;
	string function = 3;
	string chain = 4;
	string module_type = 5;
	string module_name = 6;
}

// TODO: docs
message AggregatePacketBatchLatency {
	uint32 min_latency = 1;
	uint32 max_latency = 2;
	uint64 batches = 3;
}

// TODO: docs
message AggregatePacketBatchCounters {
	uint32 min_batch_size = 1;
	uint32 max_batch_size = 2;
	uint64 mean_latency = 3;
	repeated AggregatePacketBatchLatency latencies = 4;
}

// TODO: docs
message AggregateModuleCounters {
	uint64 tx_count = 1;
	uint64 tx_bytes = 2;
	uint64 rx_count = 3;
	uint64 rx_bytes = 4;
	repeated AggregatePacketBatchCounters packet_batches = 5;
}

// TODO: docs
message AggregateModuleCountersResponse {
	repeated AggregateModuleCounters counters = 1;
}
