package gosrc_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/yanet-platform/yanet2/lint/internal/gosrc"
)

// TestIsGeneratedDetectsMarker verifies that a "Code generated ... DO NOT
// EDIT." marker before the package clause is detected, and that ordinary
// content is not.
func TestIsGeneratedDetectsMarker(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name: "marker before package clause",
			content: `// Code generated by protoc-gen-go. DO NOT EDIT.
package foo
`,
			want: true,
		},
		{
			name: "no marker",
			content: `package foo
`,
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			require.Equal(t, tt.want, gosrc.IsGenerated([]byte(tt.content)))
		})
	}
}

// TestWalkSkipsDotDirectories verifies that a .go file inside a
// dot-prefixed directory, such as a gitignored nested checkout, is not
// visited.
func TestWalkSkipsDotDirectories(t *testing.T) {
	root := t.TempDir()

	dotDir := filepath.Join(root, ".claude", "x")
	require.NoError(t, os.MkdirAll(dotDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dotDir, "mod.go"), []byte("package foo\n"), 0o644))

	var visited []string
	err := gosrc.Walk(root, nil, func(path string) error {
		visited = append(visited, path)
		return nil
	})
	require.NoError(t, err)
	require.Empty(t, visited)
}

// TestWalkSkipsUnderscoreDirectories verifies that a .go file inside an
// underscore-prefixed directory is not visited, matching the convention
// used by the Go toolchain itself.
func TestWalkSkipsUnderscoreDirectories(t *testing.T) {
	root := t.TempDir()

	underscoreDir := filepath.Join(root, "_scratch")
	require.NoError(t, os.MkdirAll(underscoreDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(underscoreDir, "mod.go"), []byte("package foo\n"), 0o644))

	var visited []string
	err := gosrc.Walk(root, nil, func(path string) error {
		visited = append(visited, path)
		return nil
	})
	require.NoError(t, err)
	require.Empty(t, visited)
}

// TestWalkVisitsFileAtDotPrefixedRoot verifies that a file directly at the
// scan root is still visited even when the root itself has a dot-prefixed
// basename.
//
// This guards against the walk callback skipping the root as if it were an
// excluded dot-directory, which would silently walk zero files.
func TestWalkVisitsFileAtDotPrefixedRoot(t *testing.T) {
	root := filepath.Join(t.TempDir(), ".hidden")
	require.NoError(t, os.MkdirAll(root, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, "mod.go"), []byte("package foo\n"), 0o644))

	var visited []string
	err := gosrc.Walk(root, nil, func(path string) error {
		visited = append(visited, path)
		return nil
	})
	require.NoError(t, err)
	require.Equal(t, []string{filepath.Join(root, "mod.go")}, visited)
}

// TestWalkRespectsExcludeFlag verifies that a directory passed via excludes
// is skipped, while a sibling directory is still visited.
func TestWalkRespectsExcludeFlag(t *testing.T) {
	root := t.TempDir()

	excludedDir := filepath.Join(root, "excluded")
	require.NoError(t, os.MkdirAll(excludedDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(excludedDir, "mod.go"), []byte("package foo\n"), 0o644))

	includedDir := filepath.Join(root, "included")
	require.NoError(t, os.MkdirAll(includedDir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(includedDir, "mod.go"), []byte("package foo\n"), 0o644))

	var visited []string
	err := gosrc.Walk(root, gosrc.ExcludeList{excludedDir}, func(path string) error {
		visited = append(visited, path)
		return nil
	})
	require.NoError(t, err)
	require.Equal(t, []string{filepath.Join(includedDir, "mod.go")}, visited)
}

// TestWalkSkipsGitIgnoredFiles verifies that Walk excludes a .go file that
// git ignores, so that a private, git-ignored tree cannot land in a tracked
// debt ledger.
//
// The root must live inside this repository's working tree, since git
// resolves ignore rules against a real repository rather than an arbitrary
// temporary directory.
func TestWalkSkipsGitIgnoredFiles(t *testing.T) {
	root, err := os.MkdirTemp(".", "walktest-")
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, os.RemoveAll(root)) })

	require.NoError(t, os.WriteFile(filepath.Join(root, ".gitignore"), []byte("ignored.go\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(root, "ignored.go"), []byte("package foo\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(root, "kept.go"), []byte("package foo\n"), 0o644))

	var visited []string
	err = gosrc.Walk(root, nil, func(path string) error {
		visited = append(visited, path)
		return nil
	})
	require.NoError(t, err)
	require.Equal(t, []string{filepath.Join(root, "kept.go")}, visited)
}
