#pragma once

#include <stddef.h>
#include <stdint.h>

////////////////////////////////////////////////////////////////////////////////
// L4 module counter
////////////////////////////////////////////////////////////////////////////////

// Module counter for L4 packets.
struct balancer_l4_module_stats {
	// Number of packets.
	uint64_t incoming_packets;

	// Failed to select virtual service.
	uint64_t select_vs_failed;

	// Packet is invalid (todo: is it the case?)
	uint64_t invalid_packets;

	// Failed to select real for virtual service.
	// For example, real is disabled, or
	// packet is not for rescheduling.
	uint64_t select_real_failed;

	// Failed to tunnel packet.
	uint64_t tunnel_failed;

	// Number of packets successfully send to the selected real.
	uint64_t outgoing_packets;
};

////////////////////////////////////////////////////////////////////////////////
// ICMP module counter
////////////////////////////////////////////////////////////////////////////////

// Counter for ICMP packets of the specific version (IPv4 or IPv6).
struct balancer_icmp_stats {
	// Number of ICMP packets.
	uint64_t incoming_packets;

	// Number of echo responses generated by balancer
	// on echo requests.
	uint64_t generated_echo_response_ipv4;

	// Failed to determinate ip of the original packet
	// because of ICMP payload too short.
	uint64_t payload_too_short_ip;

	// Original packet source address differs
	// from result packet destination address.
	uint64_t umatching_src_from_original;

	// Failed to determinate port of the original packet
	// because of ICMP payload too short.
	uint64_t payload_too_short_port;

	// Got unexpected transport of the original packet
	// (not TCP and not UDP).
	uint64_t unexpected_transport;

	// Number of packets successfully forwarded to real.
	uint64_t forwarded_packets;

	// Number of broadcasted (cloned) packets.
	uint64_t broadcasted_packets;

	// Number of clones of the packets.
	uint64_t packet_clones;
};

// Module counter for ICMP packets.
struct balancer_icmp_module_stats {
	// Counter for IPv4 packets.
	struct balancer_icmp_stats ipv4;

	// Counter for IPv6 packets.
	struct balancer_icmp_stats ipv6;
};

////////////////////////////////////////////////////////////////////////////////
// Common module counter
////////////////////////////////////////////////////////////////////////////////

// Total counts of incoming and outgoing packets.
struct balancer_common_module_stats {
	// Number of incoming packets.
	uint64_t incoming_packets;

	// Summary incoming packet bytes.
	uint64_t incoming_bytes;

	// Number of outgoing packets.
	uint64_t outgoing_packets;

	// Summary outgoing packet bytes.
	uint64_t outgoing_bytes;
};

////////////////////////////////////////////////////////////////////////////////
// Virtual Service Counter
////////////////////////////////////////////////////////////////////////////////

// Counter of the virtual service.
struct balancer_vs_stats {
	// Number of packets sent to virtual service.
	uint64_t incoming_packets;

	// Number of bytes sent to vs.
	uint64_t incoming_bytes;

	// Number of packets dropped because packet source address is
	// not allowed by virtual service.
	uint64_t packet_src_not_allowed;

	// Failed to select real for the packet, because
	// all reals are disabled.
	uint64_t no_reals;

	// Number of packets sent to real without creating session.
	uint64_t ops_packets;

	// Number of packets for which we failed to create session
	// because of session table allocation error.
	uint64_t session_table_overflow;

	// Real with which session is established is disabled
	// and packet will not be rescheduled.
	uint64_t real_is_disabled;

	// Real with which session is established is removed
	// from the config and packet will not be rescheduled.
	uint64_t real_is_removed;

	// There is no established session for packet
	// and packet does not start new session.
	uint64_t packet_not_rescheduled;

	// Total created sessions.
	uint64_t created_sessions;

	// Number of packets successfully sent to the selected real.
	uint64_t outgoing_packets;

	// Number of bytes successfully sent to the selected real.
	uint64_t outgoing_bytes;
};

////////////////////////////////////////////////////////////////////////////////
// Real counter
////////////////////////////////////////////////////////////////////////////////

// Counter of the real service.
struct balancer_real_stats {
	// Number of packets which arrived when real was disabled.
	uint64_t packets_real_disabled;

	// Number of OPS packets.
	uint64_t ops_packets;

	// Number of sessions created with real.
	uint64_t created_sessions;

	// Number of packets send to real.
	uint64_t packets;

	// Number of bytes send to real
	uint64_t bytes;
};

////////////////////////////////////////////////////////////////////////////////

// Virtual service stats info.
// Composed of virtual service registry index
// and stats.
struct balancer_vs_stats_info {
	size_t vs_registry_idx;
	struct balancer_vs_stats stats;
};

// Virtual service real info.
// Composed of real registry index
// and stats.
struct balancer_real_stats_info {
	size_t real_registry_idx;
	struct balancer_real_stats stats;
};

// Stats of the balancer module.
struct balancer_stats {
	// L4 module stats.
	struct balancer_l4_module_stats l4;

	// ICMP module stats.
	struct balancer_icmp_module_stats icmp;

	// Common module stats.
	struct balancer_common_module_stats common;

	// Virtual service stats.
	size_t vs_count;
	struct balancer_vs_stats_info *vs_info;

	// Real stats.
	size_t real_count;
	struct balancer_real_stats_info *real_info;
};

////////////////////////////////////////////////////////////////////////////////

struct agent;

// Fill balancer stats.
// Returns -1 if there is no memory to allocate stats or no module config with
// such name.
int
balancer_stats_fill(
	struct balancer_stats *stats,
	struct agent *agent,
	const char *device,
	const char *pipeline,
	const char *function,
	const char *chain,
	const char *module
);

// Fill balancer stats.
// Returns -1 if there is no memory to allocate stats.
void
balancer_stats_free(struct balancer_stats *stats, struct agent *agent);