#pragma once

#include <stddef.h>
#include <stdint.h>

////////////////////////////////////////////////////////////////////////////////
// L4 module counter
////////////////////////////////////////////////////////////////////////////////

// Module counter for L4 packets.
struct balancer_l4_module_stats {
	// Number of packets.
	uint64_t incoming_packets;

	// Failed to select virtual service.
	uint64_t select_vs_failed;

	// Packet is invalid (todo: is it the case?)
	uint64_t invalid_packets;

	// Failed to select real for virtual service.
	// For example, real is disabled, or
	// packet is not for rescheduling.
	uint64_t select_real_failed;

	// Number of packets successfully send to the selected real.
	uint64_t outgoing_packets;
};

////////////////////////////////////////////////////////////////////////////////
// ICMP module counter
////////////////////////////////////////////////////////////////////////////////

// Counter for ICMP packets of the specific version (IPv4 or IPv6).
struct balancer_icmp_module_stats {
	// Number of ICMP packets.
	uint64_t incoming_packets;

	// Failed to lookup virtual service because
	// of source address not allowed.
	uint64_t src_not_allowed;

	// Number of echo responses generated by balancer
	// on echo requests.
	uint64_t echo_responses;

	// Failed to determinate ip of the original packet
	// because of ICMP payload too short.
	uint64_t payload_too_short_ip;

	// Original packet source address differs
	// from result packet destination address.
	uint64_t unmatching_src_from_original;

	// Failed to determinate port of the original packet
	// because of ICMP payload too short.
	uint64_t payload_too_short_port;

	// Got unexpected transport of the original packet
	// (not TCP and not UDP).
	uint64_t unexpected_transport;

	// Packet destination address is not
	// recognized as virtual service.
	uint64_t unrecognized_vs;

	// Number of packets successfully forwarded to real.
	uint64_t forwarded_packets;

	// Number of broadcasted (cloned) packets.
	uint64_t broadcasted_packets;

	// Number of clones of the packets sent.
	uint64_t packet_clones_sent;

	// Number of clones of the packets received.
	uint64_t packet_clones_received;

	// Number of times we failed to make packet clone.
	uint64_t packet_clone_failures;
};

////////////////////////////////////////////////////////////////////////////////
// Common module counter
////////////////////////////////////////////////////////////////////////////////

// Total counts of incoming and outgoing packets.
struct balancer_common_module_stats {
	// Number of incoming packets.
	uint64_t incoming_packets;

	// Summary incoming packet bytes.
	uint64_t incoming_bytes;

	// Failed to process packet because of
	// unexpected network protocol.
	uint64_t unexpected_network_proto;

	// Number of packets successfully decapsulated
	// on start of the pipeline.
	uint64_t decap_successful;

	// Number of packets failed to decap
	// on start of the pipeline.
	uint64_t decap_failed;

	// Number of outgoing packets.
	uint64_t outgoing_packets;

	// Summary outgoing packet bytes.
	uint64_t outgoing_bytes;
};

////////////////////////////////////////////////////////////////////////////////
// Virtual Service Counter
////////////////////////////////////////////////////////////////////////////////

// Statistics of the virtual service.
//
// Align on cacheline because of stats are sharded
// between workers.
struct balancer_vs_stats {
	// Number of packets sent to virtual service.
	uint64_t incoming_packets;

	// Number of bytes sent to vs.
	uint64_t incoming_bytes;

	// Number of packets dropped because packet source address is
	// not allowed by virtual service.
	uint64_t packet_src_not_allowed;

	// Failed to select real for the packet, because
	// all reals are disabled.
	uint64_t no_reals;

	// Number of packets sent to real without creating session.
	uint64_t ops_packets;

	// Number of packets for which we failed to create session
	// because of session table allocation error.
	uint64_t session_table_overflow;

	// Number of echo icmp packets.
	uint64_t echo_icmp_packets;

	// Number of forwarded error icmp packets.
	uint64_t error_icmp_packets;

	// Real with which session is established is disabled
	// and packet will not be rescheduled.
	uint64_t real_is_disabled;

	// Real with which session is established is removed
	// from the config and packet will not be rescheduled.
	uint64_t real_is_removed;

	// There is no established session for packet
	// and packet does not start new session.
	uint64_t not_rescheduled_packets;

	// Number of icmp packets with source address
	// equals to the virtual service address,
	// which was broadcasted by balancer to other peers.
	uint64_t broadcasted_icmp_packets;

	// Total created sessions.
	uint64_t created_sessions;

	// Number of packets successfully sent to the selected real.
	uint64_t outgoing_packets;

	// Number of bytes successfully sent to the selected real.
	uint64_t outgoing_bytes;
};

////////////////////////////////////////////////////////////////////////////////
// Real counter
////////////////////////////////////////////////////////////////////////////////

// Statistics of the real.
//
// Align on cacheline because of stats are sharded
// between workers.
struct balancer_real_stats {
	// Number of packets which arrived when real was disabled.
	uint64_t packets_real_disabled;

	// Number of packets which arrived when real is not present
	// in the config.
	uint64_t packets_real_not_present;

	// Number of OPS packets.
	uint64_t ops_packets;

	// Number of ICMP packets.
	uint64_t error_icmp_packets;

	// Number of sessions created with real.
	uint64_t created_sessions;

	// Total number of packets send to real (including OPS and ICMP
	// packets).
	uint64_t packets;

	// Total number of bytes send to real (including OPS and ICMP packets)
	uint64_t bytes;
};

////////////////////////////////////////////////////////////////////////////////

// Virtual service stats info.
// Composed of virtual service registry index
// and stats.
struct balancer_vs_stats_info {
	size_t vs_registry_idx;
	struct balancer_vs_stats stats;
};

// Virtual service real info.
// Composed of real registry index
// and stats.
struct balancer_real_stats_info {
	size_t real_registry_idx;
	struct balancer_real_stats stats;
};

// Statistics of the balancer.
//
// Align on cacheline because of stats are sharded
// between workers.
struct balancer_stats {
	// L4 module stats.
	struct balancer_l4_module_stats l4;

	// ICMP IPv4 module stats.
	struct balancer_icmp_module_stats icmp_ipv4;

	// ICMP IPv6 module stats.
	struct balancer_icmp_module_stats icmp_ipv6;

	// Common module stats.
	struct balancer_common_module_stats common;
} __attribute__((aligned(64)));

// Statistics about balancer, virtual services and reals.
struct balancer_stats_info {
	// Statistics of the balancer.
	struct balancer_stats stats;

	// Virtual service stats.
	size_t vs_count;
	struct balancer_vs_stats_info *vs_info;

	// Real stats.
	size_t real_count;
	struct balancer_real_stats_info *real_info;
};

////////////////////////////////////////////////////////////////////////////////

struct agent;

// Fill balancer stats.
// Returns -1 if there is no memory to allocate stats or no module config with
// such name.
int
balancer_stats_info_fill(
	struct balancer_stats_info *stats,
	struct agent *agent,
	const char *device,
	const char *pipeline,
	const char *function,
	const char *chain,
	const char *module
);

// Fill balancer stats.
// Returns -1 if there is no memory to allocate stats.
void
balancer_stats_info_free(
	struct balancer_stats_info *stats, struct agent *agent
);