// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: neighbour.proto

package routepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NeighbourState represents the state of a neighbor entry.
type NeighbourState int32

const (
	NeighbourState_NUD_NONE       NeighbourState = 0
	NeighbourState_NUD_INCOMPLETE NeighbourState = 1
	NeighbourState_NUD_REACHABLE  NeighbourState = 2
	NeighbourState_NUD_STALE      NeighbourState = 4
	NeighbourState_NUD_DELAY      NeighbourState = 8
	NeighbourState_NUD_PROBE      NeighbourState = 16
	NeighbourState_NUD_FAILED     NeighbourState = 32
	NeighbourState_NUD_NOARP      NeighbourState = 64
	NeighbourState_NUD_PERMANENT  NeighbourState = 128
	NeighbourState_NUD_UNKNOWN    NeighbourState = 255
)

// Enum value maps for NeighbourState.
var (
	NeighbourState_name = map[int32]string{
		0:   "NUD_NONE",
		1:   "NUD_INCOMPLETE",
		2:   "NUD_REACHABLE",
		4:   "NUD_STALE",
		8:   "NUD_DELAY",
		16:  "NUD_PROBE",
		32:  "NUD_FAILED",
		64:  "NUD_NOARP",
		128: "NUD_PERMANENT",
		255: "NUD_UNKNOWN",
	}
	NeighbourState_value = map[string]int32{
		"NUD_NONE":       0,
		"NUD_INCOMPLETE": 1,
		"NUD_REACHABLE":  2,
		"NUD_STALE":      4,
		"NUD_DELAY":      8,
		"NUD_PROBE":      16,
		"NUD_FAILED":     32,
		"NUD_NOARP":      64,
		"NUD_PERMANENT":  128,
		"NUD_UNKNOWN":    255,
	}
)

func (x NeighbourState) Enum() *NeighbourState {
	p := new(NeighbourState)
	*p = x
	return p
}

func (x NeighbourState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NeighbourState) Descriptor() protoreflect.EnumDescriptor {
	return file_neighbour_proto_enumTypes[0].Descriptor()
}

func (NeighbourState) Type() protoreflect.EnumType {
	return &file_neighbour_proto_enumTypes[0]
}

func (x NeighbourState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NeighbourState.Descriptor instead.
func (NeighbourState) EnumDescriptor() ([]byte, []int) {
	return file_neighbour_proto_rawDescGZIP(), []int{0}
}

// ListNeighboursRequest is the request to list all neighbors.
type ListNeighboursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNeighboursRequest) Reset() {
	*x = ListNeighboursRequest{}
	mi := &file_neighbour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNeighboursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNeighboursRequest) ProtoMessage() {}

func (x *ListNeighboursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neighbour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNeighboursRequest.ProtoReflect.Descriptor instead.
func (*ListNeighboursRequest) Descriptor() ([]byte, []int) {
	return file_neighbour_proto_rawDescGZIP(), []int{0}
}

// ListNeighboursResponse contains the list of all current neighbors.
type ListNeighboursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neighbours    []*NeighbourEntry      `protobuf:"bytes,1,rep,name=neighbours,proto3" json:"neighbours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNeighboursResponse) Reset() {
	*x = ListNeighboursResponse{}
	mi := &file_neighbour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNeighboursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNeighboursResponse) ProtoMessage() {}

func (x *ListNeighboursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neighbour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNeighboursResponse.ProtoReflect.Descriptor instead.
func (*ListNeighboursResponse) Descriptor() ([]byte, []int) {
	return file_neighbour_proto_rawDescGZIP(), []int{1}
}

func (x *ListNeighboursResponse) GetNeighbours() []*NeighbourEntry {
	if x != nil {
		return x.Neighbours
	}
	return nil
}

// NeighbourEntry represents a single neighbor entry.
type NeighbourEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NextHop is the IP address of the next hop.
	NextHop string `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// LinkAddr is the MAC address of the next hop.
	LinkAddr string `protobuf:"bytes,2,opt,name=link_addr,json=linkAddr,proto3" json:"link_addr,omitempty"`
	// HardwareAddr is the MAC address of the local interface.
	HardwareAddr string `protobuf:"bytes,3,opt,name=hardware_addr,json=hardwareAddr,proto3" json:"hardware_addr,omitempty"`
	// State is the state of the neighbor entry.
	State NeighbourState `protobuf:"varint,4,opt,name=state,proto3,enum=routepb.NeighbourState" json:"state,omitempty"`
	// UpdatedAt is the timestamp when this entry was last updated.
	// This is a UNIX timestamp in seconds.
	UpdatedAt     int64 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighbourEntry) Reset() {
	*x = NeighbourEntry{}
	mi := &file_neighbour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighbourEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighbourEntry) ProtoMessage() {}

func (x *NeighbourEntry) ProtoReflect() protoreflect.Message {
	mi := &file_neighbour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighbourEntry.ProtoReflect.Descriptor instead.
func (*NeighbourEntry) Descriptor() ([]byte, []int) {
	return file_neighbour_proto_rawDescGZIP(), []int{2}
}

func (x *NeighbourEntry) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *NeighbourEntry) GetLinkAddr() string {
	if x != nil {
		return x.LinkAddr
	}
	return ""
}

func (x *NeighbourEntry) GetHardwareAddr() string {
	if x != nil {
		return x.HardwareAddr
	}
	return ""
}

func (x *NeighbourEntry) GetState() NeighbourState {
	if x != nil {
		return x.State
	}
	return NeighbourState_NUD_NONE
}

func (x *NeighbourEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_neighbour_proto protoreflect.FileDescriptor

var file_neighbour_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x70, 0x62, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x0a, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x75, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x75, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x68, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x78,
	0x74, 0x48, 0x6f, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x70, 0x62, 0x2e,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x2a, 0xb7, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x75, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x55, 0x44, 0x5f, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x55, 0x44, 0x5f, 0x49, 0x4e, 0x43,
	0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x55, 0x44,
	0x5f, 0x52, 0x45, 0x41, 0x43, 0x48, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x55, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4e,
	0x55, 0x44, 0x5f, 0x44, 0x45, 0x4c, 0x41, 0x59, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x55,
	0x44, 0x5f, 0x50, 0x52, 0x4f, 0x42, 0x45, 0x10, 0x10, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x55, 0x44,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x20, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x55, 0x44,
	0x5f, 0x4e, 0x4f, 0x41, 0x52, 0x50, 0x10, 0x40, 0x12, 0x12, 0x0a, 0x0d, 0x4e, 0x55, 0x44, 0x5f,
	0x50, 0x45, 0x52, 0x4d, 0x41, 0x4e, 0x45, 0x4e, 0x54, 0x10, 0x80, 0x01, 0x12, 0x10, 0x0a, 0x0b,
	0x4e, 0x55, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0xff, 0x01, 0x32, 0x56,
	0x0a, 0x09, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x12, 0x49, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6e, 0x65, 0x74, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x79, 0x61, 0x6e, 0x65, 0x74, 0x32, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x70, 0x62, 0x3b, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_neighbour_proto_rawDescOnce sync.Once
	file_neighbour_proto_rawDescData []byte
)

func file_neighbour_proto_rawDescGZIP() []byte {
	file_neighbour_proto_rawDescOnce.Do(func() {
		file_neighbour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neighbour_proto_rawDesc), len(file_neighbour_proto_rawDesc)))
	})
	return file_neighbour_proto_rawDescData
}

var file_neighbour_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neighbour_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_neighbour_proto_goTypes = []any{
	(NeighbourState)(0),            // 0: routepb.NeighbourState
	(*ListNeighboursRequest)(nil),  // 1: routepb.ListNeighboursRequest
	(*ListNeighboursResponse)(nil), // 2: routepb.ListNeighboursResponse
	(*NeighbourEntry)(nil),         // 3: routepb.NeighbourEntry
}
var file_neighbour_proto_depIdxs = []int32{
	3, // 0: routepb.ListNeighboursResponse.neighbours:type_name -> routepb.NeighbourEntry
	0, // 1: routepb.NeighbourEntry.state:type_name -> routepb.NeighbourState
	1, // 2: routepb.Neighbour.List:input_type -> routepb.ListNeighboursRequest
	2, // 3: routepb.Neighbour.List:output_type -> routepb.ListNeighboursResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_neighbour_proto_init() }
func file_neighbour_proto_init() {
	if File_neighbour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neighbour_proto_rawDesc), len(file_neighbour_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neighbour_proto_goTypes,
		DependencyIndexes: file_neighbour_proto_depIdxs,
		EnumInfos:         file_neighbour_proto_enumTypes,
		MessageInfos:      file_neighbour_proto_msgTypes,
	}.Build()
	File_neighbour_proto = out.File
	file_neighbour_proto_goTypes = nil
	file_neighbour_proto_depIdxs = nil
}
