// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: neighbour.proto

package routepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Neighbour_List_FullMethodName = "/routepb.Neighbour/List"
)

// NeighbourClient is the client API for Neighbour service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Neighbour is a service for viewing and managing neighbors.
type NeighbourClient interface {
	// List returns all current neighbors.
	List(ctx context.Context, in *ListNeighboursRequest, opts ...grpc.CallOption) (*ListNeighboursResponse, error)
}

type neighbourClient struct {
	cc grpc.ClientConnInterface
}

func NewNeighbourClient(cc grpc.ClientConnInterface) NeighbourClient {
	return &neighbourClient{cc}
}

func (c *neighbourClient) List(ctx context.Context, in *ListNeighboursRequest, opts ...grpc.CallOption) (*ListNeighboursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNeighboursResponse)
	err := c.cc.Invoke(ctx, Neighbour_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NeighbourServer is the server API for Neighbour service.
// All implementations must embed UnimplementedNeighbourServer
// for forward compatibility.
//
// Neighbour is a service for viewing and managing neighbors.
type NeighbourServer interface {
	// List returns all current neighbors.
	List(context.Context, *ListNeighboursRequest) (*ListNeighboursResponse, error)
	mustEmbedUnimplementedNeighbourServer()
}

// UnimplementedNeighbourServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNeighbourServer struct{}

func (UnimplementedNeighbourServer) List(context.Context, *ListNeighboursRequest) (*ListNeighboursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNeighbourServer) mustEmbedUnimplementedNeighbourServer() {}
func (UnimplementedNeighbourServer) testEmbeddedByValue()                   {}

// UnsafeNeighbourServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NeighbourServer will
// result in compilation errors.
type UnsafeNeighbourServer interface {
	mustEmbedUnimplementedNeighbourServer()
}

func RegisterNeighbourServer(s grpc.ServiceRegistrar, srv NeighbourServer) {
	// If the following call pancis, it indicates UnimplementedNeighbourServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Neighbour_ServiceDesc, srv)
}

func _Neighbour_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNeighboursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeighbourServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neighbour_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeighbourServer).List(ctx, req.(*ListNeighboursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Neighbour_ServiceDesc is the grpc.ServiceDesc for Neighbour service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Neighbour_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routepb.Neighbour",
	HandlerType: (*NeighbourServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Neighbour_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "neighbour.proto",
}
