subdir('logging')
subdir('errors')
subdir('counters')
subdir('dataplane')
subdir('controlplane')
subdir('utils')
subdir('filter') # depends on dataplane and utils libs
subdir('statemap') # generic layered hash map core
subdir('fwstate') # depends on dataplane and statemap libs
subdir('l3state') # depends on the statemap lib
subdir('fuzzing')
subdir('dataplane_ut')
subdir('tests') # depends on utils lib
