#pragma once

#include <stddef.h>
#include <stdint.h>

/**
 * Module counters for L4 packets.
 *
 * Tracks packet processing through the L4 (TCP/UDP) load balancing path,
 * including successful forwards and various failure conditions.
 */
struct balancer_l4_stats {
	/** Total L4 packets received for processing */
	uint64_t incoming_packets;

	/** Packets that failed virtual service selection (no matching VS) */
	uint64_t select_vs_failed;

	/** Invalid or malformed packets that couldn't be processed */
	uint64_t invalid_packets;

	/**
	 * Packets that failed real server selection.
	 *
	 * Incremented when:
	 * - No real servers are configured for the VS
	 * - All real servers are disabled or have zero weight
	 */
	uint64_t select_real_failed;

	/** Packets successfully forwarded to a selected real server */
	uint64_t outgoing_packets;
};

/**
 * Counters for ICMP packets of a specific IP version (IPv4 or IPv6).
 *
 * Tracks ICMP error handling including forwarding to real servers,
 * echo reply generation, and various validation failures.
 */
struct balancer_icmp_stats {
	/** Total ICMP packets received for processing */
	uint64_t incoming_packets;

	/** ICMP packets rejected due to source address policy */
	uint64_t src_not_allowed;

	/** ICMP echo replies generated by the balancer itself */
	uint64_t echo_responses;

	/**
	 * ICMP error packets with payload too short to extract IP header.
	 *
	 * ICMP errors should contain the original IP header that triggered
	 * the error. This counter tracks cases where the payload is truncated.
	 */
	uint64_t payload_too_short_ip;

	/**
	 * ICMP errors where original source doesn't match current destination.
	 *
	 * For proper ICMP error handling, the original packet's source
	 * should match the current packet's destination. This validates
	 * the error is related to traffic we forwarded.
	 */
	uint64_t unmatching_src_from_original;

	/**
	 * ICMP error packets with payload too short to extract port numbers.
	 *
	 * After extracting the IP header, we need the transport header
	 * (TCP/UDP) to get port numbers for session lookup.
	 */
	uint64_t payload_too_short_port;

	/**
	 * ICMP errors for unexpected transport protocols.
	 *
	 * The balancer only handles TCP and UDP. ICMP errors for other
	 * protocols (SCTP, DCCP, etc.) are counted here.
	 */
	uint64_t unexpected_transport;

	/**
	 * ICMP errors for unrecognized virtual services.
	 *
	 * The original packet's destination doesn't match any configured
	 * virtual service, so we can't determine where to forward the error.
	 */
	uint64_t unrecognized_vs;

	/** ICMP error packets successfully forwarded to real servers */
	uint64_t forwarded_packets;

	/**
	 * ICMP error packets broadcasted to peer balancers.
	 *
	 * In multi-balancer setups, ICMP errors may be cloned and sent
	 * to other balancer instances for session synchronization.
	 */
	uint64_t broadcasted_packets;

	/** Number of ICMP packet clones created and sent to peers */
	uint64_t packet_clones_sent;

	/** Number of ICMP packet clones received from peers */
	uint64_t packet_clones_received;

	/** Failures when attempting to create ICMP packet clones */
	uint64_t packet_clone_failures;
};

/**
 * Total counts of incoming/outgoing packets and decapsulation results.
 *
 * Tracks overall pipeline statistics including total traffic volume
 * and tunnel decapsulation operations.
 */
struct balancer_common_stats {
	/** Total packets entering the balancer pipeline */
	uint64_t incoming_packets;

	/** Total bytes of incoming packets */
	uint64_t incoming_bytes;

	/**
	 * Packets with unsupported network protocol.
	 *
	 * The balancer supports IPv4 and IPv6. Other protocols
	 * (ARP, MPLS, etc.) are counted here and dropped.
	 */
	uint64_t unexpected_network_proto;

	/** Packets successfully decapsulated from tunnels */
	uint64_t decap_successful;

	/**
	 * Packets that failed tunnel decapsulation.
	 *
	 * Incremented when:
	 * - Tunnel header is malformed
	 * - Inner packet is invalid
	 */
	uint64_t decap_failed;

	/** Total packets exiting the balancer pipeline */
	uint64_t outgoing_packets;

	/** Total bytes of outgoing packets */
	uint64_t outgoing_bytes;
};

/**
 * Aggregated statistics for the balancer.
 *
 * Contains per-module counters and optional per-service/per-real snapshots.
 * Provides a comprehensive view of balancer performance and traffic patterns.
 *
 * MEMORY MANAGEMENT:
 * - The 'vs' array is allocated by balancer_stats()
 * - Caller must free with balancer_stats_free() when done
 * - Safe to call balancer_stats_free() on partially-initialized structures
 */
struct balancer_stats {
	/** L4 (TCP/UDP) module statistics */
	struct balancer_l4_stats l4;

	/** ICMP (IPv4) module statistics */
	struct balancer_icmp_stats icmp_ipv4;

	/** ICMP (IPv6) module statistics */
	struct balancer_icmp_stats icmp_ipv6;

	/** Common pipeline statistics (all traffic) */
	struct balancer_common_stats common;

	/** Number of virtual services in the 'vs' array */
	size_t vs_count;

	/**
	 * Array of per-virtual-service statistics.
	 *
	 * Contains detailed statistics for each configured virtual service,
	 * including per-real server counters.
	 *
	 * Ownership: Allocated by balancer_stats(), freed by
	 * balancer_stats_free()
	 */
	struct named_vs_stats *vs;
};
