#pragma once

#include <stddef.h>
#include <stdint.h>

/**
 * Module counters for L4 packets.
 */
struct balancer_l4_stats {
	uint64_t incoming_packets;   // Number of L4 packets received
	uint64_t select_vs_failed;   // Failed to select virtual service
	uint64_t invalid_packets;    // Invalid or malformed packets
	uint64_t select_real_failed; // Failed to select a real (e.g., none
				     // eligible)
	uint64_t outgoing_packets; // Packets successfully sent to selected real
};

/**
 * Counters for ICMP packets of a specific IP version (IPv4 or IPv6).
 */
struct balancer_icmp_stats {
	uint64_t incoming_packets; // ICMP packets received
	uint64_t src_not_allowed;  // Source address not allowed by VS policy
	uint64_t echo_responses;   // Echo replies generated by balancer
	uint64_t payload_too_short_ip;	       // ICMP payload too short to
					       // contain original IP header
	uint64_t unmatching_src_from_original; // Original src doesn't
					       // match current dst
	uint64_t payload_too_short_port; // ICMP payload too short to contain
					 // transport header/ports
	uint64_t unexpected_transport;	 // Original transport not TCP/UDP
	uint64_t unrecognized_vs;	 // Destination not recognized as a
					 // virtual service
	uint64_t forwarded_packets;	 // ICMP forwarded to real
	uint64_t broadcasted_packets;	 // ICMP broadcasts/clones sent to peers
	uint64_t packet_clones_sent;	 // Number of packet clones created/sent
	uint64_t packet_clones_received; // Number of packet clones received
	uint64_t packet_clone_failures;	 // Failures creating packet clone
};

/**
 * Total counts of incoming/outgoing packets and decapsulation results.
 */
struct balancer_common_stats {
	uint64_t incoming_packets; // Total incoming packets at pipeline entry
	uint64_t incoming_bytes;   // Total bytes of incoming packets
	uint64_t unexpected_network_proto; // Packets with unsupported
					   // network protocol
	uint64_t decap_successful;	   // Packets successfully decapsulated
	uint64_t decap_failed;		   // Packets that failed decapsulation
	uint64_t outgoing_packets; // Total outgoing packets at pipeline exit
	uint64_t outgoing_bytes;   // Total bytes of outgoing packets
};

/**
 * Aggregated statistics for the balancer.
 *
 * Contains per-module counters and optional per-service/per-real snapshots.
 * The VS and real arrays are snapshots that may be allocated in callers.
 */
struct balancer_stats {
	struct balancer_l4_stats l4; // L4 module counters

	struct balancer_icmp_stats icmp_ipv4; // ICMP (IPv4) counters

	struct balancer_icmp_stats icmp_ipv6; // ICMP (IPv6) counters

	struct balancer_common_stats common; // Common pipeline counters

	size_t vs_count;	   // Number of entries in 'vs'
	struct named_vs_stats *vs; // Array of VS stats (length: vs_count)
};
