[package]
name = "yanet-cli-balancer2"
version = "0.1.0"
edition = "2024"
publish = false

rust-version = "1.88"

[lints]
workspace = true

[dependencies]
ync = { path = "../../../cli/core", version = "0.1", package = "yanet-cli" }
filterpb = { path = "../../../common/rust/filterpb", version = "0.1", package = "yanet-filterpb" }
commonpb = { path = "../../../common/rust/commonpb", version = "0.1", package = "yanet-commonpb" }
clap = { version = "4.5", features = ["derive", "wrap_help"] }
clap_complete = { version = "4.5", features = ["unstable-dynamic"] }
tonic = { version = "0.14", features = ["gzip"] }
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
ptree = "0.5"
tabled = { version = "0.21", default-features = false, features = ["ansi", "derive"] }
log = "0.4"
chrono = "0.4"
netip = "0.3"

[build-dependencies]
tonic-prost-build = { version = "0.14", default-features = false, features = ["transport"] }
