//! Generates the C header of the control-plane library with cbindgen.
//!
//! The header is written into the crate (`include/yanet_cp.h`) so the Go
//! bindings include a stable path; it is rewritten only when it changes.

use std::{env, fs, path::PathBuf};

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo:rerun-if-changed=src/lib.rs");
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("YANET_CP_H".into()),
        no_includes: true,
        sys_includes: vec!["stddef.h".into(), "stdint.h".into()],
        header: Some(
            "// Generated by cbindgen from rust/sdk-poc-bindgen/yanet-cp; do not edit.\n//\n// C ABI of the Rust control-plane api crates. See the crate docs for the\n// safety contract."
                .into(),
        ),
        documentation: true,
        ..Default::default()
    };
    let header = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("cbindgen failed");
    let path = crate_dir.join("include/yanet_cp.h");
    let mut generated = Vec::new();
    header.write(&mut generated);
    if fs::read(&path).ok().as_deref() != Some(generated.as_slice()) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, generated).unwrap();
    }
}
