name: Formatting check

on:
  push:
    branches: ["main"]
    paths:
      - "**.h"
      - "**.c"
  pull_request:
    branches: ["main"]
    paths:
      - "**.h"
      - "**.c"

jobs:
  c-cpp-fmt:
    name: C formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        uses: ./.github/actions/clang-format
        with:
          include: |
            *.h
            *.c
          exclude-regex: '^./subprojects/'
