name: Commit Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  commitlint:
    name: Custom commitlint linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: lint/commit/commitlint_test.sh

      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: lint/commit/commitlint.sh --subject "$PR_TITLE"

      - name: Check commit subjects
        run: |
          lint/commit/commitlint.sh \
            --range "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
