FROM ubuntu:24.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y
RUN apt install -y meson clang
RUN apt install -y python3-pyelftools libnuma-dev libpcap-dev git
RUN apt install -y gdb lldb just
RUN apt install -y golang-go
RUN apt install -y lcov
RUN apt install -y clang-format
