name: Proto Lint

on:
  push:
    paths:
      - '**/*.proto'
      - 'lint/protobuf/**'
      - 'buf.yaml'
  pull_request:
    paths:
      - '**/*.proto'
      - 'lint/protobuf/**'
      - 'buf.yaml'

jobs:
  buf-lint:
    name: Buf lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Run buf lint
        run: buf lint

  protolint:
    name: Custom protolint linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./lint/protobuf/cmd/protolint/

      - name: Run linter
        run: |
          go run ./lint/protobuf/cmd/protolint/ --exclude subprojects \
                                                --exclude common \
                                                --exclude controlplane \
                                                --exclude devices \
                                                --exclude operators/bird-adapter \
                                                --exclude modules/acl \
                                                --exclude modules/balancer \
                                                --exclude modules/balancer2 \
                                                --exclude modules/decap \
                                                --exclude modules/dscp \
                                                --exclude modules/forward \
                                                --exclude modules/fwstate \
                                                --exclude modules/nat64 \
                                                --exclude modules/pdump \
                                                --exclude modules/route \
                                                --exclude modules/route-mpls
